### ISSUE TITLE
graph execution error

### ISSUE THREAD

**Issue by Tikitaka02** [de-code/python-tf-bodypix#372]
Hello,

When I change the model to MOBILENET_FLOAT_100_STRIDE_8, I received the error below. I only used the sample code in the repo and only changed the model. The MOBILENET_FLOAT_75_STRIDE_16 and MOBILENET_FLOAT_50_STRIDE_16 were working. I appreciate your help in advance.

```
Users/takas/bodyPartSeg/bodypix/main.py
Traceback (most recent call last):
  File "c:\Users\takas\bodyPartSeg\bodypix\main.py", line 23, in <module>
    result = bodypix_model.predict_single(image_array)
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tf_bodypix\model.py", line 437, in predict_single
    tensor_map = self.predict_fn(model_input_image)
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tf_bodypix\model.py", line 134, in __call__
    return self.predict_fn(
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tf_bodypix\model.py", line 87, in __call__
    result = self.wrapped(*args, **kwargs)
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 1474, in __call__
    return self._call_impl(args, kwargs)
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 243, in _call_impl
    return super(WrappedFunction, self)._call_impl(
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 1492, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 1541, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 378, in call
    outputs = execute.execute(
  File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tensorflow\python\eager\execute.py", 
line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'MobilenetV1/Conv2d_7_depthwise/BatchNorm/batchnorm_1/add_1/conv' defined at (most recent call last):
    File "c:\Users\takas\bodyPartSeg\bodypix\main.py", line 14, in <module>
      bodypix_model = load_model(download_model(
    File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tf_bodypix\model.py", line 608, in 
load_model
      predict_fn = load_model_and_get_predict_function(model_path)
    File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tf_bodypix\model.py", line 579, in 
load_model_and_get_predict_function
      return load_using_tfjs_graph_converter_and_get_predict_function(model_path)
    File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tf_bodypix\model.py", line 564, in 
load_using_tfjs_graph_converter_and_get_predict_function
      tf_fn = tfjs_graph_converter.api.graph_to_function_v2(graph)
    File "C:\Users\takas\bodyPartSeg\bodypix\bodypix\lib\site-packages\tfjs_graph_converter\api.py", line 
420, in graph_to_function_v2
      return wrapped_import.prune(
Node: 'MobilenetV1/Conv2d_7_depthwise/BatchNorm/batchnorm_1/add_1/conv'
Current kernel implementation does not support dilations, received [1 2 2 1]
         [[{{node MobilenetV1/Conv2d_7_depthwise/BatchNorm/batchnorm_1/add_1/conv}}]] [Op:__inference_pruned_766]
```

**Comment by Tikitaka02** [comment]
I changed the tensorflow version, and it worked
