### ISSUE TITLE
SavedModel file does not exist 

### ISSUE THREAD

**Issue by txs** [de-code/python-tf-bodypix#384]
I'm trying to implement bodypix into ComfyUI
I'm having issue of error
"SavedModel file does not exist"

Cannot get it run on windows machine

**Comment by RichardLindhout** [comment]
I have the problem, looks like tfjs_graph_converter does not work anymore?

**Comment by de-code** [comment]
Is that still an issue?

**Comment by EmmaBrass** [comment]
I am having this same issue with tfjs_graph_converter.
Would love to get this working.

Here is the Traceback:

`Traceback (most recent call last):
  File "/home/emma/miniconda3/envs/rol/lib/python3.10/site-packages/tf_bodypix/model.py", line 577, in load_model_and_get_predict_function
    return load_using_saved_model_and_get_predict_function(model_path)
  File "/home/emma/miniconda3/envs/rol/lib/python3.10/site-packages/tf_bodypix/model.py", line 550, in load_using_saved_model_and_get_predict_function
    loaded = tf.saved_model.load(model_path)
  File "/home/emma/miniconda3/envs/rol/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/emma/miniconda3/envs/rol/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/emma/miniconda3/envs/rol/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/home/emma/miniconda3/envs/rol/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /home/emma/.keras/tf-bodypix/8ba301b16e59fd7bda330880a9d70e58--tfjs-models-savedmodel-bodypix-mobilenet-float-050-model-stride16/{saved_model.pbtxt|saved_model.pb}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emma/rol/visual_edit.py", line 5, in <module>
    bodypix = BodyPix()
  File "/home/emma/rol/bodypix.py", line 18, in __init__
    self.bodypix_model = load_model(download_model(
  File "/home/emma/miniconda3/envs/rol/lib/python3.10/site-packages/tf_bodypix/model.py", line 608, in load_model
    predict_fn = load_model_and_get_predict_function(model_path)
  File "/home/emma/miniconda3/envs/rol/lib/python3.10/site-packages/tf_bodypix/model.py", line 579, in load_model_and_get_predict_function
    return load_using_tfjs_graph_converter_and_get_predict_function(model_path)
  File "/home/emma/miniconda3/envs/rol/lib/python3.10/site-packages/tf_bodypix/model.py", line 562, in load_using_tfjs_graph_converter_and_get_predict_function
    raise ImportError('tfjs_graph_converter required')
ImportError: tfjs_graph_converter required`

**Comment by de-code** [comment]
Unfortunately `tfjs_graph_converter` doesn't seem to be maintained anymore. Maybe need to save a converted copy of the graphs somewhere and drop `tfjs_graph_converter`.

**Comment by EmmaBrass** [comment]
Okay might give that a go, thank you.
